apiVersion: batch/v1
kind: Job
metadata:
  name: demo-w
  namespace: default
backoffLimit: 1
spec:
  template:
    metadata:
      labels:
        app: demo-w
    restartPolicy: Never
    spec:
      # required for pod identity to apply the correct role
      serviceAccountName: demo-w
      containers:
        - name: demo-w
          image: TODO
          ports:
            - containerPort: 8080
              name: http # HTTP/2 cleartext
          env:
            - name: STATELY_STORE_ID
              value: 6978411690784381

        # The StatelyDB sidecar
        - name: statelydb
          image: public.ecr.aws/stately/dataplane:latest
          ports:
            - containerPort: 3030
              name: h2c # HTTP/2 cleartext
          env:
            # Read the access key from a k8s secret
            - name: STATELY_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-w-secret
                  key: STATELY_ACCESS_KEY
          # These resource requests/limits serve to "reserve" some space on a
          # host. The service will use the entire memory limit, but no more. You
          # will want to adjust them based on your expected workload.
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
          # The liveness probe must succeed for the pod to be considered
          # healthy. If it fails, the pod will be restarted.
          livenessProbe:
            httpGet:
              path: /health
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: demo-w
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: application
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: demo-w