apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-w2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-w2
  template:
    metadata:
      labels:
        app: demo-w2
    spec:
      # required for pod identity to apply the correct role
      serviceAccountName: demo-w
      containers:
        - name: demo-w
          image: 509869530682.dkr.ecr.us-west-2.amazonaws.com/internal/demo-w:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http # HTTP/2 cleartext
          env:
            - name: STATELY_STORE_ID
              value: "4811130409281414"

        # The StatelyDB sidecar
        - name: statelydb
          image: public.ecr.aws/stately/dataplane:latest
          ports:
            - containerPort: 3030
              name: h2c # HTTP/2 cleartext
          env:
            # Read the access key from a k8s secret
            - name: STATELY_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-w-secret
                  key: STATELY_ACCESS_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: demo-w2
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: application
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: demo-w2
